mutation LoanDisbursementTemplateCreate(
  $templateId: UUID!
  $journalId: Expression!
) {
  txTemplateCreate(
    input: {
      txTemplateId: $templateId
      code: "LOAN_DISBURSEMENT"
      description: "Payout disbursement."
      params: [
        {
          name: "loanDisbursedReceivableAccount"
          type: UUID
          description: "Loan amount-outstanding account ID."
        }
        {
          name: "checkingAccount"
          type: UUID
          description: "User Checking account ID."
        }
        {
          name: "disbursedAmount"
          type: DECIMAL
          description: "Amount of USD being issued for the loan."
        }
        {
          name: "externalId"
          type: STRING
          description: "External ID for the transaction"
        }
        {
          name: "effective"
          type: DATE
          description: "Effective date for transaction."
          default: "date()"
        }
      ]
      transaction: {
        journalId: $journalId
        effective: "params.effective"
        externalId: "params.externalId"
      }
      entries: [
        {
          accountId: "params.loanDisbursedReceivableAccount"
          units: "params.disbursedAmount"
          currency: "'USD'"
          entryType: "'LOAN_DISBURSEMENT_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.checkingAccount"
          units: "params.disbursedAmount"
          currency: "'USD'"
          entryType: "'LOAN_DISBURSEMENT_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    txTemplate {
      txTemplateId
      code
      version
    }
  }
}

mutation PostLoanDisbursementTransaction(
  $transactionId: UUID!
  $loanDisbursedReceivableAccount: UUID!
  $checkingAccount: UUID!
  $disbursedAmount: Decimal!
  $externalId: String!
) {
  transactionPost(
    input: {
      transactionId: $transactionId
      txTemplateCode: "LOAN_DISBURSEMENT"
      params: {
        loanDisbursedReceivableAccount: $loanDisbursedReceivableAccount
        checkingAccount: $checkingAccount
        disbursedAmount: $disbursedAmount
        externalId: $externalId
      }
    }
  ) {
    transaction {
      transactionId
      correlationId
      createdAt
    }
  }
}
