config {
	type: "table",
	description: "Each row represents a unique event type in credit facility.",
	assertions: {
		uniqueKey: ["PK"],
		nonNull: ["event_type"],
	},
}

WITH distinct_entries AS (
	SELECT DISTINCT
		event_type
	FROM ${ref({name: "credit_facility_events", schema: envs.currentImportSchema})}
)

SELECT
      ROW_NUMBER() OVER (ORDER BY event_type) AS PK
    , event_type
FROM distinct_entries
