describe("Chart Of Accounts", () => {
  it("should upload CSV and display chart data", () => {
    cy.uploadChartOfAccounts()

    cy.get("body")
      .contains(/Assets/i)
      .should("be.visible")
    cy.get("body")
      .contains(/Liabilities/i)
      .should("be.visible")
    cy.get("body")
      .contains(/Equity/i)
      .should("be.visible")
    cy.get("body")
      .contains(/Revenue/i)
      .should("be.visible")
    cy.get("body")
      .contains(/Expenses/i)
      .should("be.visible")

    cy.get("body")
      .contains(/Current Assets/i)
      .should("be.visible")
    cy.get("body")
      .contains(/Non-Current Assets/i)
      .should("be.visible")

    cy.takeScreenshot("2_chart_of_account_view")
  })
})
