mutation BfxAddressBackedAccountCreate(
  $input: AddressBackedAccountCreateInput!
) {
  bitfinex {
    addressBackedAccountCreate(input: $input) {
      address
      account {
        accountId
      }
    }
  }
}
