query LoanBalance(
  $journalId: UUID!
  $collateralId: UUID!
  $loanDisbursedReceivableId: UUID!
  $loanInterestReceivableId: UUID!
  $loanFacilityId: UUID!
  $interestIncomeId: UUID!
) {
  collateral: balance(
    journalId: $journalId
    accountId: $collateralId
    currency: "BTC"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanDisbursedReceivable: balance(
    journalId: $journalId
    accountId: $loanDisbursedReceivableId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanInterestReceivable: balance(
    journalId: $journalId
    accountId: $loanInterestReceivableId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  loanFacility: balance(
    journalId: $journalId
    accountId: $loanFacilityId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
  interestIncome: balance(
    journalId: $journalId
    accountId: $interestIncomeId
    currency: "USD"
  ) {
    settled {
      normalBalance {
        units
        currency
      }
    }
  }
}
