mutation CreateLoanAccounts(
  $loanCollateralAccountId: UUID!
  $loanCollateralAccountCode: String!
  $loanCollateralAccountName: String!
  $loansCollateralControlAccountSetId: UUID!
  $loanDisbursedReceivableAccountId: UUID!
  $loanDisbursedReceivableAccountCode: String!
  $loanDisbursedReceivableAccountName: String!
  $loanInterestReceivableAccountId: UUID!
  $loanInterestReceivableAccountCode: String!
  $loanInterestReceivableAccountName: String!
  $loanFacilityAccountId: UUID!
  $loanFacilityAccountCode: String!
  $loanFacilityAccountName: String!
  $interestAccountId: UUID!
  $interestAccountCode: String!
  $interestAccountName: String!
  $loansDisbursedReceivableControlAccountSetId: UUID!
  $loansInterestReceivableControlAccountSetId: UUID!
  $loansFacilityControlAccountSetId: UUID!
  $interestRevenueControlAccountSetId: UUID!
) {
  collateral: accountCreate(
    input: {
      accountId: $loanCollateralAccountId
      code: $loanCollateralAccountCode
      name: $loanCollateralAccountName
      accountSetIds: [$loansCollateralControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  disbursedReceivable: accountCreate(
    input: {
      accountId: $loanDisbursedReceivableAccountId
      code: $loanDisbursedReceivableAccountCode
      name: $loanDisbursedReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansDisbursedReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interestReceivable: accountCreate(
    input: {
      accountId: $loanInterestReceivableAccountId
      code: $loanInterestReceivableAccountCode
      name: $loanInterestReceivableAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansInterestReceivableControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  facility: accountCreate(
    input: {
      accountId: $loanFacilityAccountId
      code: $loanFacilityAccountCode
      name: $loanFacilityAccountName
      normalBalanceType: "DEBIT"
      accountSetIds: [$loansFacilityControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
  interest: accountCreate(
    input: {
      accountId: $interestAccountId
      code: $interestAccountCode
      name: $interestAccountName
      accountSetIds: [$interestRevenueControlAccountSetId]
    }
  ) {
    account {
      accountId
    }
  }
}
