mutation TermValuesCreate {
  termValuesCreate(
    input: {
      annualRate: "0.12"
      interval: END_OF_MONTH
      duration: { type: MONTHS, duration: 3 }
      liquidationCvl: "105"
      marginCallCvl: "125"
      initialCvl: "140"
    }
  ) {
    terms {
      termsId
    }
  }
}
